#!/usr/sbin/nft -f

# Config
define transmission_user = "%%transmission_user%%"
define local_lan = { %%local_lan%% }

table inet transmission_vpn {
    chain killswitch {
        type filter hook output priority -1; policy accept;

        # Allow all local traffic on the loopback interface
        oifname "lo" accept

        # Allow connection to/from LAN by User
        meta skuid $transmission_user ip daddr $local_lan accept

        # Allow any connection to/from VPN interface
        meta skuid $transmission_user oifname "tun*" accept

        # Deny any User connection outside LAN that does not use VPN
        meta skuid $transmission_user drop
    }
}
