[Service]
User=transmission
Group=jailmedia
# Clear the default Debian package ExecStart directive
ExecStart=
# Isolate the configuration path from the Debian package manager structure
ExecStart=/usr/bin/transmission-daemon -f --config-dir /var/lib/transmission-daemon/config --download-dir /mnt/incoming/transmission --incomplete-dir /mnt/torrents --logfile /var/log/transmission.log --log-info --watch-dir /mnt/transmission
